version: '3'
services:
  recruitment:
    build:
      context: ./recruitment
    ports:
        - "3000:3000"
    env_file:
      - ./recruitment/.env/development/database
      - ./recruitment/.env/development/web
    volumes:
      - ./recruitment:/usr/src/app
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack-dev-server
  recruitment-webpack-dev-server:
    build:
      context: ./recruitment
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    volumes:
      - ./recruitment:/usr/src/app
    env_file:
      - ./recruitment/.env/development/database
      - ./recruitment/.env/development/web
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  redis:
    image: redis
  recruitment-database:
    image: postgres
    env_file:
      - ./recruitment/.env/development/database
    volumes:
      - recruitment_db_data:/var/lib/postgresql/data
volumes:
  recruitment_db_data:
